import { Promo } from './types';

export const mockPromos: Promo[] = [
  {
    id: '1',
    title: '5% Cashback on Dining and Entertainment',
    description: 'Earn 5% cash back on dining and entertainment purchases, including restaurants, cafes, movie theaters, and more. Limited time offer for new cardholders.',
    bank: 'Capital One',
    category: 'Cashback',
    image: 'https://images.pexels.com/photos/6347729/pexels-photo-6347729.jpeg',
    validUntil: '2025-12-31',
    featured: true,
    isNew: true,
    externalLink: 'https://example.com/capital-one-dining',
    termsAndConditions: 'Offer valid for new cardholders only. $95 annual fee applies after the first year. Minimum spend of $500 within the first 3 months required to qualify.'
  },
  {
    id: '2',
    title: 'Double Miles on Travel Purchases',
    description: 'Earn 2X miles on all travel purchases including flights, hotels, car rentals, and cruises. Miles can be redeemed for travel or statement credits.',
    bank: 'American Express',
    category: 'Travel',
    image: 'https://images.pexels.com/photos/2007401/pexels-photo-2007401.jpeg',
    validUntil: '2025-09-30',
    featured: true,
    isNew: false,
    externalLink: 'https://example.com/amex-travel',
    termsAndConditions: 'Travel purchases must be made directly through airlines, hotels, or travel agencies to qualify for double miles.'
  },
  {
    id: '3',
    title: '0% APR on Balance Transfers for 18 Months',
    description: 'Transfer your high-interest credit card balances and pay 0% APR for 18 months. No transfer fees for the first 60 days.',
    bank: 'Citibank',
    category: 'Balance Transfer',
    image: 'https://images.pexels.com/photos/5849577/pexels-photo-5849577.jpeg',
    validUntil: '2025-08-15',
    featured: false,
    isNew: false,
    externalLink: 'https://example.com/citi-balance-transfer',
    termsAndConditions: 'After the promotional period, a variable APR of 16.99% to 26.99% will apply. Balance transfer fee of 3% (minimum $5) applies after the first 60 days.'
  },
  {
    id: '4',
    title: '$200 Welcome Bonus for New Cardholders',
    description: 'Receive a $200 statement credit when you spend $1,000 in the first 3 months of card membership. No annual fee.',
    bank: 'Chase',
    category: 'Sign-up Bonus',
    image: 'https://images.pexels.com/photos/4386151/pexels-photo-4386151.jpeg',
    validUntil: '2025-11-30',
    featured: true,
    isNew: true,
    externalLink: 'https://example.com/chase-welcome-bonus',
    termsAndConditions: 'Offer available to new cardholders who have not received a new card member bonus for this card in the past 24 months.'
  },
  {
    id: '5',
    title: '3% Cash Back on Grocery Purchases',
    description: 'Earn 3% cash back on all grocery store purchases, including supermarkets and specialty food stores. No cap on earnings.',
    bank: 'Bank of America',
    category: 'Cashback',
    image: 'https://images.pexels.com/photos/4427813/pexels-photo-4427813.jpeg',
    validUntil: '2025-10-15',
    featured: false,
    isNew: false,
    externalLink: 'https://example.com/bofa-grocery-cashback',
    termsAndConditions: 'Grocery purchases at superstores, convenience stores, warehouse clubs, or gas stations are not eligible for the 3% cash back rate.'
  },
  {
    id: '6',
    title: 'Free TSA PreCheck or Global Entry',
    description: 'Receive a statement credit for TSA PreCheck ($85) or Global Entry ($100) application fee when charged to your card.',
    bank: 'HSBC',
    category: 'Travel',
    image: 'https://images.pexels.com/photos/2265876/pexels-photo-2265876.jpeg',
    validUntil: '2025-12-31',
    featured: false,
    isNew: false,
    externalLink: 'https://example.com/hsbc-tsa-precheck',
    termsAndConditions: 'Statement credit available once every four years. Card must be in good standing at time of application fee charge.'
  },
  {
    id: '7',
    title: '10% Off at Partner Restaurants',
    description: 'Enjoy 10% off your total bill at over 5,000 participating restaurants nationwide when paying with your card.',
    bank: 'Wells Fargo',
    category: 'Dining',
    image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg',
    validUntil: '2025-06-30',
    featured: false,
    isNew: true,
    externalLink: 'https://example.com/wellsfargo-dining',
    termsAndConditions: 'Discount applied automatically at participating restaurants. Maximum discount of $50 per visit. Alcohol may be excluded.'
  },
  {
    id: '8',
    title: 'Cell Phone Protection Plan',
    description: 'Get up to $600 in cell phone protection against damage or theft when you pay your monthly cell phone bill with your card.',
    bank: 'Discover',
    category: 'Insurance',
    image: 'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg',
    validUntil: '2025-12-31',
    featured: false,
    isNew: false,
    externalLink: 'https://example.com/discover-phone-protection',
    termsAndConditions: '$25 deductible applies per claim. Maximum of two claims per 12-month period. Coverage does not include lost phones.'
  },
  {
    id: '9',
    title: '4X Points on Online Shopping',
    description: 'Earn 4 points per dollar spent on all online shopping purchases, including major retailers and specialty sites.',
    bank: 'PNC',
    category: 'Rewards',
    image: 'https://images.pexels.com/photos/5076516/pexels-photo-5076516.jpeg',
    validUntil: '2025-09-15',
    featured: false,
    isNew: true,
    externalLink: 'https://example.com/pnc-online-shopping',
    termsAndConditions: 'Online purchases must be made directly through merchant websites. Transactions through payment services like PayPal may not qualify.'
  },
  {
    id: '10',
    title: 'Free Checked Bag on Flights',
    description: 'Get your first checked bag free on all flights when you book with your card. Valid for you and up to 4 companions on the same reservation.',
    bank: 'TD Bank',
    category: 'Travel',
    image: 'https://images.pexels.com/photos/3022350/pexels-photo-3022350.jpeg',
    validUntil: '2025-08-31',
    featured: true,
    isNew: false,
    externalLink: 'https://example.com/td-checked-bag',
    termsAndConditions: 'Flights must be booked directly with the airline. Benefit applies to domestic flights only with select airline partners.'
  },
  {
    id: '11',
    title: '20% Off Hotel Bookings',
    description: 'Save 20% on hotel bookings made through the dedicated travel portal with your Premium card.',
    bank: 'Chase',
    category: 'Travel',
    image: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg',
    validUntil: '2025-07-31',
    featured: false,
    isNew: false,
    externalLink: 'https://example.com/chase-hotel-discount',
    termsAndConditions: 'Discount applies to hotel room rate only. Taxes, fees, and incidentals not included. Minimum two-night stay required.'
  },
  {
    id: '12',
    title: 'No Foreign Transaction Fees',
    description: 'Shop internationally without paying any foreign transaction fees. Perfect for travelers and online shoppers buying from overseas merchants.',
    bank: 'Capital One',
    category: 'International',
    image: 'https://images.pexels.com/photos/730547/pexels-photo-730547.jpeg',
    validUntil: '2025-12-31',
    featured: false,
    isNew: false,
    externalLink: 'https://example.com/capitalone-no-foreign-fees',
    termsAndConditions: 'Card must be used for direct purchases. Transactions made through currency conversion services may incur additional fees.'
  }
];